version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:17.0.10
    steps:
      - checkout
      - run:
          name: Ensure test results directory exists
          command: mkdir -p /home/circleci/project/target/surefire-reports/
      - run:
          name: Run tests
          command: mvn test
      - store_test_results:
          path: /home/circleci/project/target/surefire-reports/

workflows:
  version: 2
  test_workflow:
    jobs:
      - test