version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:21.0
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-deps-v1-{{ checksum "pom.xml" }}
            - maven-deps-v1-
      - run:
          name: Ensure test results directory exists
          command: mkdir -p /home/circleci/project/target/surefire-reports/
      - run:
          name: Download Dependencies
          command: mvn dependency:resolve
      - save_cache:
          paths:
            - ~/.m2
          key: maven-deps-v1-{{ checksum "pom.xml" }}
      - run:
          name: Run Tests
          command: mvn clean test -Dtest.environment=prod
      - run:
          name: Generate Test Report
          command: mvn surefire-report:report-only
          when: always
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/surefire-reports
      - store_artifacts:
          path: target/site

workflows:
  test-workflow:
    jobs:
      - test